package com.yan.performanceAmountQuery.model;

import java.io.Serializable;

public class Performanceamount extends PerformanceamountKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performanceamount.amount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performanceamount.agent_id
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performanceamount.amount
     *
     * @return the value of performanceamount.amount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performanceamount.amount
     *
     * @param amount the value for performanceamount.amount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performanceamount.agent_id
     *
     * @return the value of performanceamount.agent_id
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performanceamount.agent_id
     *
     * @param agentId the value for performanceamount.agent_id
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", amount=").append(amount);
        sb.append(", agentId=").append(agentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}