package com.yan.performanceAmountQuery.model;

import java.io.Serializable;

public class PerformanceamountKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performanceamount.agentName
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private String agentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performanceamount.year
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performanceamount.month
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performanceamount.agentName
     *
     * @return the value of performanceamount.agentName
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public String getAgentname() {
        return agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performanceamount.agentName
     *
     * @param agentname the value for performanceamount.agentName
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public void setAgentname(String agentname) {
        this.agentname = agentname == null ? null : agentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performanceamount.year
     *
     * @return the value of performanceamount.year
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performanceamount.year
     *
     * @param year the value for performanceamount.year
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performanceamount.month
     *
     * @return the value of performanceamount.month
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performanceamount.month
     *
     * @param month the value for performanceamount.month
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", agentname=").append(agentname);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}