package com.yan.performanceAmountQuery.mapper;

import com.yan.performanceAmountQuery.model.Performanceamount;
import com.yan.performanceAmountQuery.model.PerformanceamountExample;
import com.yan.performanceAmountQuery.model.PerformanceamountKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PerformanceamountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    long countByExample(PerformanceamountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int deleteByExample(PerformanceamountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int deleteByPrimaryKey(PerformanceamountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int insert(Performanceamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int insertSelective(Performanceamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    List<Performanceamount> selectByExample(PerformanceamountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    Performanceamount selectByPrimaryKey(PerformanceamountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Performanceamount record, @Param("example") PerformanceamountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int updateByExample(@Param("record") Performanceamount record, @Param("example") PerformanceamountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int updateByPrimaryKeySelective(Performanceamount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performanceamount
     *
     * @mbg.generated Thu Jun 21 10:37:12 CST 2018
     */
    int updateByPrimaryKey(Performanceamount record);
}