package com.yan.packageAmountCalculate.model;

import java.io.Serializable;

public class Performance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.packageType
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private String packagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.packageAmount
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private Integer packageamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.agent_id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.year
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.month
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.id
     *
     * @return the value of performance.id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.id
     *
     * @param id the value for performance.id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.packageType
     *
     * @return the value of performance.packageType
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public String getPackagetype() {
        return packagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.packageType
     *
     * @param packagetype the value for performance.packageType
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setPackagetype(String packagetype) {
        this.packagetype = packagetype == null ? null : packagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.packageAmount
     *
     * @return the value of performance.packageAmount
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public Integer getPackageamount() {
        return packageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.packageAmount
     *
     * @param packageamount the value for performance.packageAmount
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setPackageamount(Integer packageamount) {
        this.packageamount = packageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.agent_id
     *
     * @return the value of performance.agent_id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.agent_id
     *
     * @param agentId the value for performance.agent_id
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.year
     *
     * @return the value of performance.year
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.year
     *
     * @param year the value for performance.year
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.month
     *
     * @return the value of performance.month
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.month
     *
     * @param month the value for performance.month
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Tue Jun 19 15:49:37 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", packagetype=").append(packagetype);
        sb.append(", packageamount=").append(packageamount);
        sb.append(", agentId=").append(agentId);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}